recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view
from .views import logout_view

urlpatterns = [  
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home
from .views import RecipeListView
from .views import RecipeDetailsView
from .views import records
from .views import about_me

app_name = 'recipes'  

urlpatterns = [
   path('', home, name='home'),
   path('list/', RecipeListView.as_view(), name='list'),
   path('list/<pk>', RecipeDetailsView.as_view(), name='details'),
   path('search/', records, name='search'),
   path('about_me/', about_me, name='about_me')
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Recipe(models.Model):
    name = models.CharField(max_length=60)

    ingredients = models.CharField(max_length=300, help_text='seperated by a comma')

    cooking_time = models.FloatField(help_text='in minutes')

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')

        if self.cooking_time < 10 and len(ingredients) < 4:
            difficulty = 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 4:
            difficulty = 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 4:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 4:
            difficulty = 'Hard'
        return difficulty
    
    pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
       return reverse('recipes:details', kwargs={'pk': self.pk})

recipes/forms.py
from django import forms  #import django forms

CHART__CHOICES = (        #specify choices as a tuple
    ('#1', 'Bar chart'),  # when user selects "Bar chart", it is stored as "#1"
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

class RecipesSearchForm(forms.Form):
    recipe_name = forms.CharField(max_length=120)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

recipe_project/views.py
from django.shortcuts import render, redirect  
#Django authentication libraries           
from django.contrib.auth import authenticate, login, logout
#Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm

#define a function view called login_view that takes a request from user
def login_view(request):
    #initialize:
    #error_message to None                                 
    error_message = None   
    #form object with username and password fields                             
    form = AuthenticationForm()                            


    #when user hits "login" button, then POST request is generated
    if request.method == 'POST':       
        #read the data sent by the form via POST request                   
        form =AuthenticationForm(data=request.POST)

        #check if form is valid
        if form.is_valid():                                
            username=form.cleaned_data.get('username')      #read username
            password = form.cleaned_data.get('password')    #read password

            #use Django authenticate function to validate the user
            user=authenticate(username=username, password=password)

            if user is not None:   #if user is authenticated
            #then use pre-defined Django function to login
                login(request, user)                
                return redirect('recipes:list') #& send the user to desired page
        
        else:                                               #in case of error
            error_message ='ooops.. something went wrong'   #print error message

    #prepare data to send from view to template
    context ={                                             
        'form': form,                                 #send the form data
        'error_message': error_message                     #and the error_message
    }

    #load the login page using "context" information
    return render(request, 'auth/login.html', context)

#define a function view called logout_view that takes a request from user
def logout_view(request):                                  
    logout(request)          #the use pre-defined Django function to logout
    return render(request, 'auth/success.html') #after logging out go to login form (or whichever page you want)

recipes/views.py
from django.shortcuts import render                     #imported by default
from django.views.generic import ListView, DetailView   #to display lists
from .models import Recipe
#to protect class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
#to protect function-based views
from django.contrib.auth.decorators import login_required
from .forms import RecipesSearchForm
import pandas as pd
from .utils import get_recipe_name_from_id, get_chart

# Create your views here.

def home(request):
   return render(request, 'recipes/home.html')

def about_me(request):
   return render(request, 'recipes/about_me.html')

class RecipeListView(LoginRequiredMixin, ListView):   #class-based view
   model = Recipe                       #specify model
   template_name = 'recipes/main.html'  #specify template 

class RecipeDetailsView(LoginRequiredMixin, DetailView):      
   model = Recipe                     
   template_name = 'recipes/details.html'   

@login_required
def records(request):
      form = RecipesSearchForm(request.POST or None)

      recipe_df = None
      recipe_name = None
      chart = None

      if request.method == 'POST':
         recipe_name = request.POST.get('recipe_name')
         chart_type = request.POST.get('chart_type')

         qs = Recipe.objects.filter(name=recipe_name)

         if qs:
            recipe_df = pd.DataFrame(qs.values())
            recipe_df['id']=recipe_df['id'].apply(get_recipe_name_from_id)
            chart = get_chart(chart_type, recipe_df, labels=recipe_df['name'].values)
            recipe_df = recipe_df.to_html()

      context = {
         'form': form,
         'recipe_df': recipe_df,
         'recipe_name': recipe_name,
         'chart': chart,
      }

      return render(request, 'recipes/search.html', context)

recipes/templates/recipes/about_me.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>About Me</title>
    </head>
    
    <body style="background-color: whitesmoke">
        <div style="font-family: monospace; text-align: center; margin-top: 40px;">

            <div>
                <h1 style="font-size: 48px;">About Me</h1>

                <p style="font-size: 24px;">Hello! My name is William Demczyk. I separated from the Army November,<br> 2022 after serving three years; nine months out of those being on rotation in 
                    South Korea,<br> and I now reside in Dayton, Ohio. I enjoy gaming and working out, and playing with my English Mastiff, Athena.<br>
                    I'm currently taking online classes for Web Development, and I'm excited for my new career.</p>

                <p style="font-size: 24px;"><a href="https://github.com/pleplu/my-portfolio">My Portfolio</a></p>

                <div style="font-size: 24px;">
                    <a href="{%url 'recipes:list' %}">Return</a>
                </div>

            </div>
        </div>
    </body>
</html>

recipes/templates/recipes/details.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <title>Recipe Details</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="static/style.css"> 
    </head>

    <body style="background-color: whitesmoke">
        <div style="font-family: monospace; text-align: center; font-size: 24px; margin-top: 40px;">
            <h2>{{object.name}}</h2>
        
            <b>Ingredients: </b> {{object.ingredients}} <br>
        
            <b>Cooking Time (min): </b> {{object.cooking_time}} <br>
        
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br><br>
        
            <img src="{{object.pic.url}}" width="256" height="256" border="2" />
            <br><br>
            <a href="{%url 'recipes:list' %}">Back</a>
        </div>
    </body>
</html>

recipes/templates/recipes/home.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <title>Recipe App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="static/style.css"> 
        <script src="{% static 'recipes/home.js' %}" defer></script>
    </head>

    <body style="background-color: whitesmoke">
        <div style="text-align: center; margin-top: 40px; font-family: monospace;">
            <h1 style="font-size: 48px; margin-bottom: 15px; text-decoration: underline;">Welcome to my Recipe App</h1>
            <a style="font-size: 24px;" href ="{%url 'login' %}">Login</a>
            <br>
            <br>
            <img style="margin-top: 10px;" src="{% static 'recipes/images/tea.webp' %}" alt="home" width="900" height="600" border="2">
        </div>
    </body>
</html>

recipes/templates/recipes/main.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <title>Recipes List</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="static/style.css"> 
    </head>

    <body style="background-color: whitesmoke;">
        <div style="font-family: monospace; text-align: center; margin-top: 40px;">

            <h1 style="font-size: 48px; margin-bottom: 15px; text-decoration: underline;">Recipes List</h1>   
            
            <div>
                <form action="" method="GET">
                    {% csrf_token %}
                    <input type="text" name="recipe_search" class="form_search_input" id="searchbar" placeholder="Search for a Reecipe" onkeyup="search_recipe()" />
                </form>
                <br>
                <div class="search_results" style="display: none;">
                    {% for object in object_list %}
                    <p class="recipe_searched" style="font-size: 24px; margin-top: -10px;"><a class="recipe_name" href="{{object.get_absolute_url}}">{{object.name}}</a></p>
                    {% endfor %}
                </div>
            </div>

            <div style="font-size: 24px;">
                <a href="{%url 'recipes:search' %}" class="logout_btn">See Recipe Data</a>
            </div>
            <br>
            <div style="font-size: 24px;">
                <a href ="{%url 'recipes:about_me' %}">About Me</a>
            </div>
            <br>
            <div style="font-size: 24px;">
                <a href ="{%url 'logout' %}">Logout</a>
            </div>

            <div>
                {% for object in object_list %} 
                    <div style="margin-bottom: -16px;">
                        <h2 style="font-size: 24px;">{{object.name}}</h2>
                    </div>
                    
                    <a href ="{{object.get_absolute_url}}"><img src="{{object.pic.url}}" width="200" height="200" border="2" /></a>
                    <br><br>
                {% endfor %}
            </div>
        </div>
        <script src="{% static 'recipes/main.js' %}"></script>
    </body>
</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
<html>
    <head>
        <title>Recipe Search</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="static/style.css"> 
    </head>

    <body style="background-color: whitesmoke;">
        <div style="font-family: monospace; text-align: center;">
            <h1 style="font-size: 48px; text-decoration: underline;">Search for a recipe</h1>

            <form style="font-size: 24px;" action="" method="POST">
                {% csrf_token %}
                {{form}}
                <button type="submit">Search</button>
            </form>

            <br><br>
            <div style="width: 600px; margin: auto;">
                {% if recipe_df %}
                {{recipe_df|safe}}
            </div>
            <br>
            <img src="data:image/png;base64, {{chart|safe}}">
            {% else %}
            <p style="font-size: 24px;">no data</p>
            {% endif %}
            <br><br>

            <a style="font-size: 24px;" href="{%url 'recipes:list' %}">Back</a>
        </div>
    </body>
</html>